version: '3'
services:
        backend:
                build:
                        context: ./Backend
                volumes:
                        - ./Backend/autocompletion:/autocompletion
                ports:
                        - "8080:8000"
                env_file:
                        - ./Database/db.secret
                        - ./hostip.secret 
        database:
                build:
                        context: ./Database
                        dockerfile: Dockerfile
                ports:
                        - "5000:27017" 
                volumes:
                        - ./Database/db_data:/database
                        - ./Database/db_log:/db_log
                env_file:
                        - ./Database/db.secret
        react:
                build:
                        context: ./React
                        dockerfile: Dockerfile
                ports: 
                        - "5001:3000"
                volumes: 
                        - ./React/react:/react
                env_file: 
                        - ./hostip.secret
