FROM ubuntu:18.04

# Install Django 
RUN echo "todo:install django"

# Install facilitating dependences
RUN apt install vim

# Map code base to host 
RUN mkdir /autocompletion
VOLUME ["/autocompletion"]

WORKDIR /autocompletion 

